myproject/blog/urls.py
from django.urls import path

from .views import home, detail

app_name = "blog"
urlpatterns = [
    path('', home, name="home"),
    path('article/<slug:slug>/', detail, name="detail"),
]

myproject/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/blog/models.py
from datetime import datetime

from django.db import models


class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس دسته بندی")
    status = models.BooleanField(default=True, verbose_name="آیا نمایش داده شود؟")
    position = models.IntegerField(verbose_name="پوزیشن")

    class Meta:
        verbose_name: str = "دسته بندی"
        verbose_name_plural: str = "دسته بندی ها"
        ordering: list[str] = ['position']

    def __str__(self):
        return self.title


# Create your models here.
class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published')
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    category = models.ManyToManyField(Category, verbose_name="دسته بندی")
    description = models.TextField()
    thumbnail = models.ImageField(upload_to="images")
    publish_datetime = models.DateTimeField(default=datetime.utcnow())
    creation_datetime = models.DateTimeField(auto_now_add=True)
    last_update_datetime = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)

    def __str__(self):
        return self.title

    def category_published(self):
        return self.category.filter(status=True)

    objects = ArticleManager()
    # published_objects = ArticleManager()

myproject/blog/views.py
from urllib.request import Request

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from .models import Article


# Create your views here.
def home(request: Request):
    # return HttpResponse("Hello World")
    # context: dict = {
    #     "username": "Amirhossein",
    #     "age": 27,
    #     "job": "Programmer"
    # }

    context: dict = {
        # "articles": Article.objects.filter(status="p").order_by("-publish_datetime")
        # "articles": Article.objects.filter(status="p").order_by("-publish_datetime")
        "articles": Article.objects.published().order_by("-publish_datetime")
        # "articles": Article.published_objects.published().order_by("-publish_datetime")
    }
    return render(request, "blog/home.html", context)


def api(request: Request):
    return JsonResponse({"title": "سلام دنیا"})


def detail(request: Request, slug: str):
    context: dict = {
        # "article": get_object_or_404(Article, slug=slug, status='p')
        "article": get_object_or_404(Article.objects.published(), slug=slug)
        # "article": get_object_or_404(Article.published_objects.published(), slug=slug)
    }
    return render(request, "blog/detail.html", context)

myproject/blog/templates/blog/detail.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<img src="{{ article.thumbnail.url }}" alt="{{ article.title }}">
<!--<h1><a href="/article/{{ article.slug }}/">title: {{ article.title }}</a></h1>-->
<h1><a href="{% url 'blog:detail' article.slug %}">title: {{ article.title }}</a></h1>
<p>
    description: {{ article.description }}
</p>
<p>
    publish_datetime: {{ article.publish_datetime }}
</p>
</body>
</html>

myproject/blog/templates/blog/home.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    This is home.html
</div>
{% for article in articles %}
<img src="{{ article.thumbnail.url }}" alt="">
<!--<h1><a href="/article/{{ article.slug }}/">title: {{ article.title }}</a></h1>-->
<h1><a href="{% url 'blog:detail' article.slug %}">title: {{ article.title }}</a></h1>
<p>
    description: {{ article.description }}
</p>
{% endfor %}
</body>
</html>

myproject/blog/templates/blog/partials/category_navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>